---
title: "module 1"
author: "Hannah Kim"
date: "2024-10-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="C:/Users/hanna/OneDrive/Documents/pstat197/GitHub/module1-7")
```

```{r, message = F}
# Load in libraries
library(tidyverse)
library(tidymodels)
library(modelr)
library(rsample)
library(yardstick)
library(randomForest)
library(infer)
library(glmnet)
library(ggplot2)

load("data\\biomarker-clean.RData")
```

## -- LASSO Regression
```{r}
set.seed(102024)

biomarker <- biomarker_clean %>%
  select(-ados) %>%
  mutate(class = as.numeric(group == 'ASD'))

# Partitions 
biomarker_split <- biomarker %>%
  initial_split(prop = 0.8)

bio_train <- training(biomarker_split)
bio_test <- testing(biomarker_split)

predictors <- training(biomarker_split) %>%
  select(-c(group, class)) %>%
  as.matrix()

response <- training(biomarker_split) %>%
  pull(class)

# Selecting optimal lambda
cv_out <- cv.glmnet(predictors, 
                    response, 
                    family = 'binomial',
                    nfolds = 5, 
                    alpha = 1, 
                    type.measure = 'deviance')
cv_out_df <- tidy(cv_out)
plot(cv_out)

#choosing lambda for final model
lambda <- exp(-2.5)
best_model <- glmnet(predictors,
                     response,
                     family = 'binomial', 
                     lambda = lambda)

best_model_df <- tidy(best_model)

#selecting proteins for panel
protein_select <- best_model_df %>% 
  filter(term != '(Intercept)') %>% 
  pull(term)
protein_select

#rebuild training and testing with new panel
bio_model <- biomarker_clean %>% 
  select(group, any_of(protein_select)) %>% 
  mutate(class = as.numeric(group == 'ASD')) %>% 
  select(-group)

set.seed(46400)
bio_partitions <- bio_model %>% 
  initial_split(prop = 0.8)

bio_x_train <- training(bio_partitions)

fit <- glm(class ~., data = bio_x_train,
                 family = 'binomial')

#Using yardstick package to find accuracy of model with the 5 protein panel
class_metric <- metric_set(sensitivity, 
                           specificity, 
                           accuracy)

pred_df <- testing(bio_partitions) %>% 
  add_predictions(fit, type = 'response') %>% 
  mutate(pred.class = (pred > 0.5),
         group = factor(class, labels = c('TD', 'ASD')),
         pred.group = factor(pred.class, labels = c('TD', 'ASD'))) 

pred_df %>% class_metric(truth = group, estimate = pred.group, event_level = 'second')
```

## -- Logistic Regression
```{r}
# Selecting subset
proteins_sstar <- c("DERM", "RELT", "IgD", "PTN", "FSTL1")
biomarker_sstar <- biomarker_clean %>%
  select(group, any_of(proteins_sstar)) %>%
  mutate(class = (group == 'ASD')) %>%
  select(-group)

# Split into training and test data
set.seed(101400)
biomarker_partitions <- biomarker_sstar %>%
  initial_split(prop = 0.8)

# fit logistic regression model to training set
fit <- glm(class ~ ., 
           data = training(biomarker_partitions), 
           family = 'binomial')

# evaluate errors on test set
class_metrics <- metric_set(sensitivity, 
                            specificity, 
                            accuracy)

testing(biomarker_partitions) %>%
  add_predictions(fit, type = 'response') %>%
  mutate(est = as.factor(pred > 0.5), tr_c = as.factor(class)) %>%
  class_metrics(estimate = est,
              truth = tr_c, pred,
              event_level = 'second')
```


